-- Database Penagisa Food Corner
-- Jalankan di Supabase SQL Editor atau PostgreSQL.

create extension if not exists pgcrypto;

create table if not exists public.comments (
    id uuid primary key default gen_random_uuid(),
    name text not null check (char_length(trim(name)) between 1 and 100),
    food text not null check (char_length(trim(food)) between 1 and 100),
    rating smallint not null check (rating between 1 and 5),
    message text not null check (char_length(trim(message)) between 1 and 2000),
    status text not null default 'approved' check (status in ('pending', 'approved', 'rejected')),
    created_at timestamptz not null default now()
);
 
create table if not exists public.link_clicks (
    id bigint generated by default as identity primary key,
    link_url text not null,
    source text,
    referrer text,
    visitor_id text,
    device_type text check (device_type in ('mobile', 'tablet', 'desktop', 'unknown')),
    user_agent text,
    clicked_at timestamptz not null default now()
);

create table if not exists public.sales_orders (
    id uuid primary key default gen_random_uuid(),
    customer_name text not null check (char_length(trim(customer_name)) between 1 and 100),
    customer_contact text,
    order_type text not null check (order_type in ('Delivery', 'Takeaway')),
    address text,
    note text,
    status text not null default 'new' check (status in ('new', 'queued', 'preparing', 'waiting_courier', 'on_the_way', 'delivered', 'confirmed', 'completed', 'cancelled')),
    total_amount numeric(12, 2) not null default 0 check (total_amount >= 0),
    whatsapp_sent_at timestamptz,
    created_at timestamptz not null default now()
);

alter table public.sales_orders add column if not exists payment_method text not null default 'COD';
alter table public.sales_orders add column if not exists payment_status text not null default 'pending';
alter table public.sales_orders add column if not exists payment_confirmed_at timestamptz;
alter table public.sales_orders add column if not exists payment_proof_url text;
alter table public.sales_orders add column if not exists address text;
alter table public.sales_orders add column if not exists delivery_confirmation text check (delivery_confirmation in ('received', 'not_received'));
alter table public.sales_orders add column if not exists delivery_confirmation_at timestamptz;
alter table public.sales_orders drop constraint if exists sales_orders_status_check;
alter table public.sales_orders add constraint sales_orders_status_check check (status in ('new', 'queued', 'preparing', 'waiting_courier', 'on_the_way', 'delivered', 'confirmed', 'completed', 'cancelled'));

create table if not exists public.sales_order_items (
    id uuid primary key default gen_random_uuid(),
    order_id uuid not null references public.sales_orders(id) on delete cascade,
    product_id integer not null,
    product_name text not null,
    quantity integer not null check (quantity > 0),
    unit_price numeric(12, 2) not null check (unit_price >= 0),
    subtotal numeric(12, 2) generated always as (quantity * unit_price) stored
);

create index if not exists comments_created_at_idx on public.comments (created_at desc);
create index if not exists link_clicks_clicked_at_idx on public.link_clicks (clicked_at desc);
create index if not exists sales_orders_created_at_idx on public.sales_orders (created_at desc);
create index if not exists sales_orders_status_idx on public.sales_orders (status);
create index if not exists sales_order_items_order_id_idx on public.sales_order_items (order_id);

create or replace view public.menu_sales_summary as
select
    soi.product_name,
    sum(soi.quantity)::integer as total_quantity,
    sum(soi.subtotal) as total_sales
from public.sales_order_items soi
join public.sales_orders so on so.id = soi.order_id
where so.status <> 'cancelled'
group by soi.product_name;

insert into storage.buckets (id, name, public)
values ('payment-proofs', 'payment-proofs', true)
on conflict (id) do update set public = true;

drop policy if exists "public can upload payment proofs" on storage.objects;
create policy "public can upload payment proofs"
    on storage.objects for insert
    with check (bucket_id = 'payment-proofs');
drop policy if exists "public can read payment proofs" on storage.objects;
create policy "public can read payment proofs"
    on storage.objects for select
    using (bucket_id = 'payment-proofs');

create or replace view public.admin_dashboard as
select
    (select count(*) from public.comments where status = 'approved') as total_comments,
    (select coalesce(round(avg(rating)::numeric, 1), 0) from public.comments where status = 'approved') as average_rating,
    (select count(*) from public.link_clicks) as total_link_clicks,
    (select count(*) from public.sales_orders where status <> 'cancelled') as total_orders,
    (select coalesce(sum(total_amount), 0) from public.sales_orders where status in ('confirmed', 'completed')) as total_sales,
    (select count(*) from public.sales_orders where status = 'new') as pending_orders;

-- Komentar publik boleh dikirim, tetapi hanya komentar approved yang boleh dibaca publik.
alter table public.comments enable row level security;
drop policy if exists "public can submit comments" on public.comments;
create policy "public can submit comments"
    on public.comments for insert
    with check (status = 'pending');
drop policy if exists "public can read approved comments" on public.comments;
create policy "public can read approved comments"
    on public.comments for select
    using (status = 'approved');

-- Dashboard admin memakai gerbang admin di frontend untuk memoderasi komentar.
drop policy if exists "admin dashboard can read comments" on public.comments;
create policy "admin dashboard can read comments"
    on public.comments for select
    using (true);
drop policy if exists "admin dashboard can approve comments" on public.comments;
create policy "admin dashboard can approve comments"
    on public.comments for update
    using (true)
    with check (status in ('pending', 'approved', 'rejected'));
drop policy if exists "admin dashboard can delete comments" on public.comments;
create policy "admin dashboard can delete comments"
    on public.comments for delete
    using (true);

-- Statistik klik hanya menerima data dari frontend dan tidak dibuka untuk pembacaan publik.
alter table public.link_clicks enable row level security;
drop policy if exists "public can record link clicks" on public.link_clicks;
create policy "public can record link clicks"
    on public.link_clicks for insert
    with check (true);

-- Pesanan dapat dibuat dari frontend. Data pengelolaan dashboard sebaiknya dibaca
-- memakai akun admin/backend yang sudah diautentikasi.
alter table public.sales_orders enable row level security;
drop policy if exists "public can submit sales orders" on public.sales_orders;
create policy "public can submit sales orders"
    on public.sales_orders for insert
    with check (status = 'new');
drop policy if exists "public can return submitted sales orders" on public.sales_orders;
create policy "public can return submitted sales orders"
    on public.sales_orders for select
    using (true);
drop policy if exists "admin can update sales orders" on public.sales_orders;
create policy "admin can update sales orders"
    on public.sales_orders for update
    using (true)
    with check (
        payment_status in ('pending', 'awaiting_verification', 'paid', 'cod_confirmed')
        and status in ('new', 'queued', 'preparing', 'waiting_courier', 'on_the_way', 'delivered', 'confirmed', 'completed', 'cancelled')
    );
drop policy if exists "admin can delete sales orders" on public.sales_orders;
create policy "admin can delete sales orders"
    on public.sales_orders for delete
    using (true);

alter table public.sales_order_items enable row level security;
drop policy if exists "public can submit order items" on public.sales_order_items;
create policy "public can submit order items"
    on public.sales_order_items for insert
    with check (true);
drop policy if exists "public can read order items" on public.sales_order_items;
create policy "public can read order items"
    on public.sales_order_items for select
    using (true);

-- Aktifkan policy SELECT/UPDATE/DELETE untuk role admin/authenticated sesuai
-- sistem login yang dipakai saat frontend mulai membaca dashboard ini.
